# Generated by Django 3.1.1 on 2020-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('keyword', models.CharField(choices=[('DV', 'Доставка'), ('AC', 'НДС')], max_length=3)),
                ('order_price_condition', models.CharField(choices=[('LTE', '<='), ('LT', '<'), ('GTE', '>='), ('GT', '>'), ('EQ', '=')], help_text='Условный оператор, который должен выполниться, для использования этой скидки, например, если в этом поле указан знак ">", то если "цена заказа" > "цена скидки", то скидка активируется относительно данного заказа', max_length=3)),
                ('orders', models.ManyToManyField(related_name='taxes', to='store.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('keyword', models.CharField(choices=[('FDV', 'Бесплатная доставка'), ('BO', 'Большой заказ')], max_length=3)),
                ('order_price_condition', models.CharField(choices=[('LTE', '<='), ('LT', '<'), ('GTE', '>='), ('GT', '>'), ('EQ', '=')], help_text='Условный оператор, который должен выполниться, для использования этой скидки, например, если в этом поле указан знак ">", то если "цена заказа" > "цена скидки", то скидка активируется относительно данного заказа', max_length=3)),
                ('orders', models.ManyToManyField(related_name='discounts', to='store.Order')),
            ],
        ),
    ]
