# Generated by Django 3.1.1 on 2020-10-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_discount_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='condition_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tax',
            name='condition_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
