# Generated by Django 3.1.1 on 2020-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20201012_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='discounts', to='store.Order'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='order_price_condition',
            field=models.CharField(choices=[('LTE', '<='), ('LT', '<'), ('GTE', '>='), ('GT', '>'), ('EQ', '=')], help_text='Условный оператор, который должен выполниться, для использования этого налога, например, если в этом поле указан знак ">", то если "цена заказа" > "цена налога", то налог активируется относительно данного заказа', max_length=3),
        ),
        migrations.AlterField(
            model_name='tax',
            name='orders',
            field=models.ManyToManyField(null=True, related_name='taxes', to='store.Order'),
        ),
    ]
