# Generated by Django 3.1.1 on 2020-10-12 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20201012_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='discounts', to='store.Order'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='orders',
            field=models.ManyToManyField(blank=True, null=True, related_name='taxes', to='store.Order'),
        ),
    ]
