# Generated by Django 3.1.1 on 2020-10-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20201014_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='keyword',
            field=models.CharField(choices=[('MO', 'Средний заказ'), ('BO', 'Большой заказ')], max_length=3, verbose_name='Вид налога'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage_price',
            field=models.BooleanField(default=False, verbose_name='Цена налога указана в процентах'),
        ),
    ]
